### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by Emuzex** [HikariKnight/quickpassthrough#11]
Since running the script, the main system (manjaro) cannot use the dedicated nvidia card.  I have since reinstalled the system, but the situation has not changed.  If I install nvidia's nonfree drivers, the system won't boot.  If the system starts with free drivers, there is no problem, but the graphics performance is very poor due to the lack of a dedicated card

Can u help me to get the dedicated card back?

Thank you

**Comment by HikariKnight** [comment]
hi @Emuzex, it is odd that a reinstall of manjaro did not undo the changes, even though a reinstall should not have been necessary as you can just press E in your bootloader when selecting what to boot and just remove the vfio_pci lines to disable the passthrough for 1 boot so that you can fix things.
 
all the original files are found in the backup folder. the script also tells you to make a backup/snapshot of your system before you continue, in case you run into any severe issues.
![image](https://user-images.githubusercontent.com/2557889/216563444-a7e5bd5a-71f9-48e1-97a0-83e3ae165182.png)

If none of those files above mentions vfio or vfio_pci in their content on your current install, then the current issues you are having are not related to the changes done by the script and might instead be related to an nvidia driver+kerner incompatibility as the nvidia driver can be very picky about what kernels it supports.

Anyways if the script is run a 2nd time and the backup folder exists, a new backup will not be made as  the new files might contain files that have been modified.

To restore the backup you just copy the files inside the backup folder back to your system and update your bootloader (with update-grub, grub-mkconfig or kernelstub depending on which one you use for your system)

you also can manually delete `/etc/modprobe.d/vfio.conf`, even though it should not be necessary to delete it as all it says is to load the vfio_pci driver before graphic drivers, it doesnt grab any hardware as we do that through the bootloader instead so people can shut it off manually if they run into issues.

also if you use systemd-boot instead of grub you will have to remove the vfio_pci kernel arguments from your config, since this script uses kernelstub for that you can check your arguments with `sudo kernelstub -p` and remove the arguments with `sudo kernelstub -d "vfio_pci.ids=10de:1f02,10de:10f9,10de:1ada,10de:1adb vfio_pci.disable_vga=1"`, the ids in that command are from my system, edit them to match what yours were from the previous command.

for grub you just have to run `sudo update-grub` or the equivalent command on manjaro to generate the old grub config once you have moved the default grub file back.

the script also says it is not made for systems with a single graphic card, as it sounds like you might have run it on a system with just 1 graphic card.
![image](https://user-images.githubusercontent.com/2557889/216566360-83563c3e-4feb-4622-a53b-75ffa39e737a.png)
![image](https://user-images.githubusercontent.com/2557889/216566494-5ab3b10d-b1c1-41d7-8011-7973ee8a0f24.png)

**Comment by Emuzex** [comment]
Yes its works now. Thank you for quick help.

**Comment by HikariKnight** [comment]
> 

awesome! :+1:
