### ISSUE TITLE
Plans dynamic binding/releasing?

### ISSUE THREAD

**Issue by Joelangelo** [HikariKnight/quickpassthrough#15]
Hi, I must say that i really like your work! It worked flawlessly for me!

I'm just wondering if you have any ideas or plans for making a dynamic version of this? Lets say i want to detach my 3070 when i start my VM and then reattach it again to my host when i shut the VM down.

**Comment by HikariKnight** [comment]
> Hi, I must say that i really like your work! It worked flawlessly for me!
> 
> I'm just wondering if you have any ideas or plans for making a dynamic version of this? Lets say i want to detach my 3070 when i start my VM and then reattach it again to my host when i shut the VM down.

Hi, very happy you have gotten use for it!

I have been playing around with the idea of this and been testing several things (conveniently my system can do both singleGPU and dualGPU passthrough!), but the conclusion at this time always ends up the same sadly.
The scripts needed to free up the GPU from the host are very system by system dependent and there is no reliable way currently to achieve the intended behavior each time.

if it was as simple as just stopping display-manager.service and unloading the driver modules it would have been great, but sadly it is not.

use wayland? well the wayland compositor might still be running even though the display manager is stopped.
What if you use a non standard display manager? what if the user starts the desktop from the tty?

It is sadly too many variables to account for and the risk for a random program to somehow linger and be in use by the GPU when the display manager is killed is too high and if the driver is not fully unloaded before passing it to the VM, congratulations you got yourself a frozen system that needs to be hard reset.

So **for now** it is removed from the scope of the project until this situation improves.

However you can set up your own custom scripts using the vfio tools hook helper
https://passthroughpo.st/simple-per-vm-libvirt-hooks-with-the-vfio-tools-hook-helper/

an example of a begin script would be
```bash
#!/bin/bash
# Helpful to read output when debugging
set -x

source /etc/libvirt/hooks/vfio.conf

# Stop display manager
systemctl stop display-manager.service
## Uncomment the following line if you use GDM and/or a window manager (replace awesome with your WM)
killall gdm-x-session
killall -9 awesome

# If your user is not uid 1000 change it to your uid or username
pulse_pid=$(pgrep -u hk pulseaudio)
pipewire_pid=$(pgrep -u hk pipewire)
wayland_pid=$(pgrep wayland)
kill $pulse_pid
kill $pipewire_pid
kill $wayland_pid


# Unbind VTconsoles (change these to match your vtconsoles)
echo 0 > /sys/class/vtconsole/vtcon0/bind
echo 0 > /sys/class/vtconsole/vtcon1/bind

# Unbind EFI-Framebuffer (uncomment if you use an nvidia card)
#echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind

# Avoid a Race condition by waiting 2 seconds. This can be calibrated to be shorter or longer if required for your system
sleep 5

# Unload amdgpu
modprobe -r amdgpu

# Unload nvidia driver (uncomment if you are passing through an nvidia card)
#modprobe -r nvidia
#modprobe -r nvidia_drm
#modprobe -r gpu_sched
#modprobe -r ttm
#modprobe -r drm_kms_helper
#modprobe -r i2c_algo_bit
#modprobe -r drm
#modprobe -r snd_hda_intel

# Unbind the GPU from display driver (replace 0000_42_00_1 and 2 with your PCI IDs)
virsh nodedev-detach pci_0000_$DEVICE_VIDEO
virsh nodedev-detach pci_0000_$DEVICE_AUDIO

# Load VFIO Kernel Module  
modprobe vfio
modprobe vfio_pci
modprobe vfio_iommu_type1 
```

then to restore on release (some cards or even OSes require a full host reboot instead! yes i am aware of vendor-reset but that does not cover all cards and doesn't fix the issue where certain OSes literally locks the card on shutdown)
```bash
#!/bin/bash
set -x

source /etc/libvirt/hooks/vfio.conf

#sleep 5
#echo 1 > /sys/bus/pci/devices/0000:42:00.1/remove
#echo 1 > /sys/bus/pci/devices/0000:42:00.0/remove
#echo 1 > /sys/bus/pci/rescan
#sleep 2
 
# Re-Bind GPU
virsh nodedev-reattach pci_0000_$DEVICE_AUDIO
virsh nodedev-reattach pci_0000_$DEVICE_VIDEO

sleep 3
modprobe amdgpu
sleep 3

#sleep 10

# Rebind VT consoles
echo 1 > /sys/class/vtconsole/vtcon0/bind
# Some machines might have more than 1 virtual console. Add a line for each corresponding VTConsole
echo 1 > /sys/class/vtconsole/vtcon1/bind

#nvidia-xconfig --query-gpu-info > /dev/null 2>&1
#echo "efi-framebuffer.0" > /sys/bus/platform/drivers/efi-framebuffer/bind

# Restart Display Manager
killall -9 Xorg
sleep 7
systemctl start display-manager.service
```

and finally here is an example of the vfio.conf file i have in /etc/libvirt/hooks
```bash
DEVICE_VIDEO="44_00_0"
DEVICE_AUDIO="44_00_1"
DEVICE_USB=""
DEVICE_SERIAL=""
```

as you can see it is a very messy system with too many wires that can be stumbled over since a single random application can make it all fall over (example being a window manager or a random application communicating with the gpu in the background)

**Comment by Joelangelo** [comment]
I see. Huge thanks for giving me such an elaborate answer though! I really appreciate it.

**Comment by HikariKnight** [comment]
> I see. Huge thanks for giving me such an elaborate answer though! I really appreciate it.

no problem @Joelangelo!
I figured if someone would land here through web search then they would also benefit from the information and not just you :)
